/* pack.js — Built-in offline lesson (works with no AI): Class 8 Science · Force and Pressure (NCERT-aligned).
   Used as a genuine fallback when the AI teacher is unavailable. Question bank is finite and says so when used up. */
(function(){
  const P = window.Pack = {};
  P.force = {
    title: 'Force and Pressure', subject: 'Science', subjectKind: 'physics', level: 'Class 8',
    match: /force|pressure|push|pull|balanced|friction force|atmospheric/i,
    concepts: [
      { id:'c1', name:'Force is a push or a pull' },
      { id:'c2', name:'Effects of a force' },
      { id:'c3', name:'Balanced & unbalanced forces (net force)' },
      { id:'c4', name:'Contact and non-contact forces' },
      { id:'c5', name:'Pressure = Force ÷ Area' },
      { id:'c6', name:'Pressure in liquids and gases' },
    ],
    diagnostic: [
      { type:'mcq', difficulty:'easy', concept:'c1', stem:'Which of these is the best description of a force?', options:['Something only living things can apply','A push or a pull on an object','The speed of a moving object','The weight of an object only'], answer:1, trapOptions:[0], optionNotes:['Magnets and the Earth apply forces too.','Correct: every force is a push or a pull.','Speed is motion, not force.','Weight is one force among many.'], explanation:'A force is a push or a pull, and it arises from an interaction between two objects.' },
      { type:'tf', difficulty:'easy', concept:'c2', stem:'True or false: a force can change the shape of an object.', answer:0, explanation:'Pressing a ball of dough flattens it: force can change shape.' },
      { type:'mcq', difficulty:'medium', concept:'c3', stem:'Two teams pull a rope with equal force in opposite directions. What happens to the rope?', options:['It moves towards the stronger team','It does not move, because the forces are balanced','It moves in both directions','It breaks immediately'], answer:1, trapOptions:[0], explanation:'Equal and opposite forces cancel: net force is zero, so the state of motion does not change.' },
      { type:'short', difficulty:'medium', concept:'c5', stem:'Why is it easier to cut vegetables with a sharp knife than with a blunt one?', keyPoints:['sharp edge has a smaller area','same force on smaller area gives more pressure','pressure = force / area'], modelAnswer:'A sharp knife has a very small cutting area. The same force on a smaller area produces greater pressure (pressure = force/area), so it cuts easily.', explanation:'Pressure increases when the area decreases for the same force.' },
    ],
    sections: [
      { level:'Basic', heading:'What is a force?', body:'A **force** is a **push or a pull**. Kicking a football, opening a door and lifting a bag all need a force.\n\n- A force always comes from an **interaction** between at least two objects (your foot and the ball).\n- The SI unit of force is the **newton (N)**.\n- A force has both a **size (magnitude)** and a **direction**.', example:'When you pull a drawer, your hand interacts with the drawer. When you let go, the pull stops.', checkpoint:{ type:'mcq', difficulty:'easy', concept:'c1', stem:'What is the SI unit of force?', options:['Pascal','Newton','Joule','Metre'], answer:1, explanation:'Force is measured in newtons (N). The pascal is the unit of pressure.' } },
      { level:'Foundation', heading:'What can a force do?', body:'A force can:\n\n1. **Start** a stationary object moving (push a toy car).\n2. **Stop** a moving object (catch a ball).\n3. **Change its speed** (a harder kick makes the ball go faster).\n4. **Change its direction** (a batter hits the ball back).\n5. **Change its shape** (press a balloon or dough).\n\nChanges 1–4 are all changes in the **state of motion**, meaning speed and/or direction.', example:'A cricket ball bowled at the batter changes direction and speed when hit: two effects of one force.', checkpoint:{ type:'tf', difficulty:'easy', concept:'c2', stem:'True or false: a force can only make things move faster, never slower.', answer:1, explanation:'A force can also slow down or stop an object, like brakes on a bicycle.' } },
      { level:'Intermediate', heading:'Balanced and unbalanced forces', body:'When several forces act on one object, what matters is the **net force**:\n\n- Forces in the **same direction add up**.\n- Forces in **opposite directions subtract**, and the object is pushed in the direction of the larger force.\n- If the net force is **zero**, the forces are **balanced**. The state of motion does **not** change.\n- If the net force is **not zero**, the forces are **unbalanced**. The object speeds up, slows down or changes direction.', example:'A box has 10 N pushing right and 4 N pushing left. Net force = 10 − 4 = **6 N to the right**.', checkpoint:{ type:'numerical', difficulty:'medium', concept:'c3', stem:'Two friends push a cart to the right with 30 N and 25 N. A third pushes left with 15 N. What is the net force (in N, to the right)?', answer:40, unit:'N', tolerance:0.01, explanation:'30 + 25 − 15 = 40 N to the right.' } },
      { level:'Intermediate', heading:'Contact and non-contact forces', body:'**Contact forces** act only when objects touch:\n- **Muscular force** (from our muscles)\n- **Friction** (opposes motion between surfaces in contact)\n\n**Non-contact forces** act without touching:\n- **Magnetic force** (magnets attract or repel)\n- **Electrostatic force** (a rubbed balloon attracts bits of paper)\n- **Gravitational force** (the Earth pulls everything towards it; this pull is the object’s weight)', example:'A ball rolling on the ground slows down and stops because of friction, a contact force.', checkpoint:{ type:'mcq', difficulty:'medium', concept:'c4', stem:'Which of these is a non-contact force?', options:['Friction','Muscular force','Electrostatic force','The push of your hand on a door'], answer:2, trapOptions:[0], explanation:'Electrostatic force acts at a distance, e.g. a charged comb attracting paper.' } },
      { level:'Advanced', heading:'Pressure: force spread over an area', body:'**Pressure** is the force acting **per unit area** (force acting perpendicular to a surface):\n\n> Pressure = Force ÷ Area\n\n- SI unit: newton per square metre (N/m²), called the **pascal (Pa)**.\n- **Same force, smaller area → more pressure.** That is why knives are sharpened and nails have pointed tips.\n- **Same force, larger area → less pressure.** That is why bags have wide straps and heavy trucks have many wide tyres.', example:'A box weighing 600 N rests on a base of 2 m × 1.5 m = 3 m². Pressure = 600 ÷ 3 = **200 Pa**. Stand it on a smaller face and the pressure increases.', checkpoint:{ type:'numerical', difficulty:'medium', concept:'c5', stem:'A force of 200 N acts on an area of 0.5 m². What is the pressure in pascals?', answer:400, unit:'Pa', tolerance:0.01, explanation:'200 ÷ 0.5 = 400 Pa.' } },
      { level:'Mastery', heading:'Pressure in liquids and gases', body:'- **Liquids exert pressure on the walls** of their container, not just the bottom. Water spurts out of holes in the side of a bottle.\n- Liquid pressure **increases with depth**. Water from a lower hole spurts farther. Dams are built **thicker at the bottom** for this reason.\n- A liquid at the same depth exerts **equal pressure** on the walls all around.\n- **Gases** exert pressure too (the air inside a balloon pushes outward).\n- The air around us exerts **atmospheric pressure**, about **100,000 Pa (≈ 10⁵ Pa)** at sea level. We aren’t crushed because the pressure inside our bodies roughly balances it.', example:'Press a rubber sucker onto a smooth surface. Most of the air between them is pushed out, so the atmospheric pressure outside holds it in place.', checkpoint:{ type:'mcq', difficulty:'hard', concept:'c6', stem:'Why is the wall of a dam made thicker at the bottom?', options:['Because water is heavier at the top','Because liquid pressure increases with depth','Because atmospheric pressure is higher at the top','To make the dam look stable'], answer:1, trapOptions:[0], explanation:'Deeper water exerts more pressure, so the base must withstand the greatest pressure.' } },
    ],
    scenes: [
      { title:'A push or a pull', level:'Basic', narration:'Let’s start with something you did this morning. You opened a door. Did you push or pull? Either way, you applied a force. A force is simply a push or a pull, and it always needs two objects interacting: your hand and the door. We measure force in newtons, written N.', board:['Force = push or pull','Unit: newton (N)'], visual:{ type:'forces', object:'Door', unit:'N', forces:[{ dir:'right', label:'Push', size:5 }] } },
      { title:'What a force can do', level:'Foundation', narration:'Now think about a football. A kick can start it moving. A goalkeeper can stop it. A harder kick makes it faster, and a header changes its direction. Squeeze a balloon and its shape changes. So a force can change speed, direction or shape. The first ones together we call the state of motion.', board:['Start · stop · speed up', 'Change direction · change shape'], visual:{ type:'process', steps:['Start moving','Stop','Change speed','Change direction','Change shape'] } },
      { title:'Adding forces', level:'Intermediate', narration:'Here is a box with ten newtons pushing right and four newtons pushing left. Forces in opposite directions subtract. Think for a second: which way will it move? Ten minus four is six newtons, to the right. That leftover is the net force.', board:['Opposite → subtract','Same direction → add'], visual:{ type:'forces', object:'Box', unit:'N', forces:[{ dir:'right', label:'Push', size:10 },{ dir:'left', label:'Push', size:4 }] }, checkpoint:{ type:'mcq', difficulty:'medium', concept:'c3', stem:'If both pushes were 7 N in opposite directions, what would happen to the box at rest?', options:['It moves right','It moves left','It stays at rest (balanced)','It moves up'], answer:2, explanation:'Equal and opposite forces are balanced: net force is zero.' } },
      { title:'Balanced vs unbalanced', level:'Intermediate', narration:'When the net force is zero we call the forces balanced, and nothing about the motion changes. A book resting on a table has balanced forces: gravity pulls it down and the table pushes it up. When the net force is not zero, the forces are unbalanced, and the object speeds up, slows down or turns.', board:['Net = 0 → balanced','Net ≠ 0 → motion changes'], visual:{ type:'forces', object:'Book', unit:'N', forces:[{ dir:'down', label:'Weight', size:8 },{ dir:'up', label:'Table push', size:8 }] } },
      { title:'Touching or not', level:'Intermediate', narration:'Some forces need contact, like muscular force and friction. Friction is why a rolling ball finally stops. Others act from a distance: magnets, a rubbed balloon attracting paper, and gravity pulling everything towards the Earth. Common mistake: friction is not a non-contact force. It needs surfaces touching.', board:['Contact: muscular, friction','Non-contact: magnetic, electrostatic, gravity'], visual:{ type:'compare', left:{ title:'Contact', points:['Muscular force','Friction'] }, right:{ title:'Non-contact', points:['Magnetic','Electrostatic','Gravitational'] } } },
      { title:'Pressure', level:'Advanced', narration:'Why does a sharp knife cut better than a blunt one, even with the same force? Because pressure is force divided by area. The sharp edge has a tiny area, so the pressure is huge. Pressure is measured in newtons per square metre, called pascals.', board:['P = F ÷ A','Unit: pascal (Pa)'], visual:{ type:'equation', steps:['Pressure = Force ÷ Area','P = F ÷ A','200 N ÷ 0.5 m²','P = 400 Pa'] }, checkpoint:{ type:'numerical', difficulty:'medium', concept:'c5', stem:'A 600 N box rests on 3 m². Pressure in Pa?', answer:200, unit:'Pa', tolerance:0.01, explanation:'600 ÷ 3 = 200 Pa.' } },
      { title:'Deeper means more pressure', level:'Mastery', narration:'Liquids push on the walls of their container too. Make three holes in a bottle at different heights. Water from the lowest hole spurts farthest, because liquid pressure increases with depth. That is exactly why dams are thicker at the bottom.', board:['Liquid pressure ↑ with depth','Pushes on walls, not just bottom'], visual:{ type:'bars', title:'Liquid pressure vs depth (water)', unit:'kPa', items:[{ label:'1 m', value:9.8 },{ label:'2 m', value:19.6 },{ label:'5 m', value:49 },{ label:'10 m', value:98 }] } },
      { title:'Recap and teach-back', level:'Mastery', narration:'Let’s recap. A force is a push or pull that can change motion or shape. Net force decides what happens: balanced means no change. Contact forces need touching; non-contact forces don’t. Pressure is force per area, and liquid pressure grows with depth. Now, could you teach this to a friend in one minute? You will try that soon.', board:['Force → motion/shape','P = F ÷ A'], visual:{ type:'process', steps:['Force','Net force','Contact / non-contact','Pressure = F÷A','Liquids & gases'] } },
    ],
    bank: [
      { stage:'practice', type:'mcq', difficulty:'medium', concept:'c2', stem:'A moving football is kicked sideways. Which effect of force is mainly shown?', options:['Change in shape only','Change in direction of motion','Change in mass','No effect'], answer:1, explanation:'A sideways kick changes the direction of motion.' },
      { stage:'practice', type:'numerical', difficulty:'medium', concept:'c5', stem:'A girl weighing 400 N stands on one foot of area 0.02 m². What pressure does she exert on the ground (Pa)?', answer:20000, unit:'Pa', tolerance:0.01, explanation:'400 ÷ 0.02 = 20,000 Pa.' },
      { stage:'practice', type:'short', difficulty:'medium', concept:'c3', stem:'Explain what “balanced forces” means, with one everyday example.', keyPoints:['forces equal in size and opposite in direction','net force is zero','no change in state of motion','valid example like tug of war draw or book on table'], modelAnswer:'Balanced forces are equal in size and act in opposite directions, so the net force is zero and the state of motion does not change. Example: a book resting on a table, where gravity down is balanced by the table’s push up.', explanation:'Zero net force means no change in motion.' },
      { stage:'practice', type:'mcq', difficulty:'easy', concept:'c4', stem:'A comb rubbed in dry hair attracts small bits of paper. Which force is this?', options:['Magnetic force','Muscular force','Electrostatic force','Friction'], answer:2, trapOptions:[0], explanation:'A charged object exerts electrostatic force.' },
      { stage:'practice', type:'fill', difficulty:'easy', concept:'c5', stem:'The SI unit of pressure is the ____.', answer:'pascal', accept:['Pa','pascals','N/m²','newton per square metre'], explanation:'1 pascal = 1 N/m².' },
      { stage:'hard', type:'assertion', difficulty:'hard', concept:'c6', stem:'Assertion (A): Water spurts out farthest from the lowest hole of a tall bottle. Reason (R): Liquid pressure increases with depth.', answer:0, explanation:'Both are true and R explains A.' },
      { stage:'hard', type:'long', difficulty:'hard', concept:'c5', stem:'A heavy truck has many wide tyres, but a drawing pin has a sharp tip. Explain both designs using the idea of pressure.', keyPoints:['pressure = force / area','truck spreads weight over large area to reduce pressure on road','pin concentrates force on tiny area to increase pressure','same principle used in opposite ways'], modelAnswer:'Pressure = force/area. The truck’s many wide tyres spread its weight over a large area, lowering pressure so it doesn’t sink or damage the road. The pin’s sharp tip has a tiny area, so even a small thumb force gives very high pressure and it pierces the board. It is the same principle used in opposite ways.', explanation:'Large area lowers pressure; small area raises it.' },
      { stage:'hard', type:'numerical', difficulty:'very hard', concept:'c5', stem:'A 900 N crate can rest on a face measuring 1.5 m × 1 m or on a face measuring 1 m × 0.5 m. By how many pascals does the pressure increase when it is turned onto the smaller face?', answer:1200, unit:'Pa', tolerance:0.01, explanation:'Large face: 900 ÷ 1.5 = 600 Pa. Small face: 900 ÷ 0.5 = 1800 Pa. Increase = 1200 Pa.' },
      { stage:'hard', type:'mcq', difficulty:'hard', concept:'c3', stem:'A car moves at a steady speed in a straight line. What can you say about the forces on it?', options:['There must be no forces acting on it','The forward force is greater than friction','The forces are balanced: net force is zero','Only gravity acts on it'], answer:2, trapOptions:[0,1], explanation:'Steady speed in a straight line means no change in motion, so the net force is zero (balanced), even though forces act.' },
      { stage:'apply', type:'case', difficulty:'hard', concept:'c6', context:'Riya’s family is building an overhead water tank. The plumber suggests placing the tank on the roof rather than at ground level, and making the pipe joints near the bottom of the tank extra strong.', stem:'Using ideas about liquid pressure, explain both suggestions.', keyPoints:['higher tank gives greater depth/height of water above taps so more pressure at taps','water flows out with more force','pressure is greatest at the bottom of the tank','joints at the bottom must withstand highest pressure'], modelAnswer:'Liquid pressure increases with depth. A tank on the roof puts a tall column of water above the taps, so water reaches them with high pressure. Inside the tank, pressure is greatest at the bottom, so joints there must be strongest to avoid leaks.', explanation:'Depth of liquid decides pressure.' },
      { stage:'apply', type:'application', difficulty:'hard', concept:'c5', stem:'Your school bag strap is thin and hurts your shoulder. Suggest a change and explain it with pressure.', keyPoints:['use wider strap','larger area','same weight so lower pressure','less pain'], modelAnswer:'Use a wider (padded) strap. The bag’s weight stays the same, but a larger area means lower pressure on the shoulder, so it hurts less.', explanation:'Increase area to reduce pressure.' },
      { stage:'explain', type:'short', difficulty:'medium', concept:'c1', stem:'In your own words, why do we say a force needs at least two objects?', keyPoints:['force arises from interaction','one object pushes or pulls another','example'], modelAnswer:'A force is an interaction: one object pushes or pulls on another. There is always something applying the force and something receiving it, such as a foot and a ball.', explanation:'Force = interaction between objects.' },
      { stage:'challenge', type:'challenge', difficulty:'unfamiliar', concept:'c6', stem:'Astronauts’ spacesuits are pressurised. Using what you know about atmospheric pressure and pressure inside our bodies, explain why a suit is needed in space, where there is almost no air.', keyPoints:['on Earth atmospheric pressure outside balances pressure inside the body','in space there is almost no outside pressure','body fluids/gases would push outward unbalanced','suit supplies outside pressure to balance'], modelAnswer:'On Earth, the pressure inside our bodies is roughly balanced by atmospheric pressure (about 10⁵ Pa). In space there is almost no air, so nothing balances the internal pressure and body fluids and gases would push outward dangerously. A pressurised suit provides that outside pressure, keeping forces balanced.', explanation:'Transfer of balanced-pressure idea to a new situation.' },
      { stage:'recall', type:'mcq', difficulty:'easy', concept:'c6', stem:'Roughly what is atmospheric pressure at sea level?', options:['About 10 Pa','About 1,000 Pa','About 100,000 Pa','About 10,000,000 Pa'], answer:2, explanation:'About 10⁵ Pa.' },
      { stage:'recall', type:'tf', difficulty:'easy', concept:'c4', stem:'True or false: gravitational force acts only when objects touch.', answer:1, explanation:'Gravity is a non-contact force.' },
      { stage:'fix', type:'mcq', difficulty:'medium', concept:'c1', stem:'Which situation best shows that a force needs two interacting objects?', options:['A book lying alone in empty space','A magnet pulling an iron nail towards it','A car parked with its engine off','A ball sitting still on the floor with nothing touching it except the floor'], answer:1, explanation:'The magnet and the nail interact: one pulls on the other.' },
      { stage:'fix', type:'tf', difficulty:'easy', concept:'c2', stem:'True or false: a force applied opposite to motion can bring a moving bicycle to rest.', answer:0, explanation:'Brakes apply a force opposite to motion and stop the bicycle.' },
      { stage:'fix', type:'numerical', difficulty:'medium', concept:'c3', stem:'A box at rest has 20 N pushing it right and 20 N pushing it left. What is the net force on it (in N)?', answer:0, unit:'N', explanation:'20 − 20 = 0 N. The forces are balanced, so it stays at rest.' },
      { stage:'fix', type:'mcq', difficulty:'easy', concept:'c4', stem:'A ball thrown upward comes back down. Which force pulls it down?', options:['Muscular force','Friction','Gravitational force','Magnetic force'], answer:2, trapOptions:[1], explanation:'The Earth’s gravitational force pulls the ball down, without touching it.' },
      { stage:'fix', type:'mcq', difficulty:'medium', concept:'c5', stem:'Why can a camel walk on sand more easily than a horse?', options:['Camels are lighter','Camels’ wide feet spread their weight over a larger area, reducing pressure','Sand is harder under camels','Camels walk faster'], answer:1, trapOptions:[0], explanation:'Larger area → less pressure → feet sink less.' },
      { stage:'fix', type:'short', difficulty:'medium', concept:'c6', stem:'Why does water spurt out farther from a hole near the bottom of a bottle than from a hole near the top?', keyPoints:['liquid pressure increases with depth','bottom hole is deeper','greater pressure pushes water out faster/farther'], modelAnswer:'Liquid pressure increases with depth. The bottom hole has more water above it, so the pressure there is greater and pushes water out faster and farther.', explanation:'Depth → pressure.' },
      { stage:'review', type:'mcq', difficulty:'medium', concept:'c5', stem:'Which change would increase the pressure a box exerts on the floor?', options:['Placing it on its largest face','Placing it on its smallest face','Painting it','Moving it to another room'], answer:1, explanation:'Smaller area → greater pressure (same weight).' },
      { stage:'review', type:'short', difficulty:'medium', concept:'c3', stem:'A 12 N push to the right and a 5 N push to the left act on a trolley. Describe what happens and why.', keyPoints:['net force 7 N','to the right','unbalanced forces','trolley starts moving / speeds up to the right'], modelAnswer:'The forces are unbalanced: net force = 12 − 5 = 7 N to the right, so the trolley starts moving (or speeds up) to the right.', explanation:'Opposite forces subtract.' },
      { stage:'review', type:'application', difficulty:'hard', concept:'c6', stem:'Why do deep-sea divers need special suits, while swimmers in a pool don’t?', keyPoints:['liquid pressure increases with depth','deep sea pressure is very high','pool is shallow so small pressure','suit protects body'], modelAnswer:'Liquid pressure increases with depth. Deep in the sea the water pressure is enormous and could harm the body, so divers need strong suits. A pool is shallow, so the extra pressure is small.', explanation:'Depth → pressure.' },
    ],
    teachbackPoints: ['force is a push or pull from an interaction','effects: change speed, direction, shape','net force; balanced means no change in motion','contact vs non-contact examples','pressure = force / area, unit pascal','liquid pressure increases with depth; atmosphere exerts pressure'],
    sheet: {
      keyConcepts: ['Force = push or pull, from an interaction (unit: newton, N)','Force can change speed, direction (state of motion) and shape','Net force: add same direction, subtract opposite','Balanced (net 0) → no change in motion; unbalanced → motion changes','Pressure = Force ÷ Area (unit: pascal, Pa = N/m²)','Liquid pressure increases with depth; liquids push on walls; atmospheric pressure ≈ 10⁵ Pa'],
      formulas: ['P = F ÷ A','1 Pa = 1 N/m²','Net force = sum (same dir.) or difference (opposite dir.)'],
      mistakes: ['Thinking friction is a non-contact force','Thinking a moving object must have an unbalanced force (steady motion = balanced)','Mixing up the newton (force) and the pascal (pressure)','Forgetting to convert area to m²'],
      hooks: ['“Sharp = small area = big pressure”','“Dams are fat at the feet”'],
      questions: ['Why are dams thicker at the bottom?','Why do camels walk easily on sand?','Calculate pressure: 500 N on 0.25 m²'],
      visual: { type:'equation', steps:['P = F ÷ A','↑F → ↑P','↓A → ↑P'] }
    }
  };

  /* Offline question picker: unasked bank items for a stage, honestly reporting when exhausted. */
  P.questions = (t, stage, count) => {
    const pack = P[t.builtin]; if(!pack) return [];
    const stageMap = { practice:['practice'], hard:['hard'], apply:['apply'], explain:['explain','practice'], challenge:['challenge'], recall:['recall'], review:['review','recall','practice'], fix:['practice','hard','review','recall'], refresh:['review','recall'] };
    const allowed = stageMap[stage] || [stage];
    const fresh = pack.bank.filter(q => allowed.includes(q.stage) && !t.asked.some(s => M.similarity(s, q.stem) > 0.9));
    const pick = [];
    for(const q of fresh){ const v = Quiz.validate(q, t, pick); if(v) pick.push(v); if(pick.length >= count) break; }
    return pick;
  };
  P.fixQuestion = (t, concept) => {
    const pack = P[t.builtin]; if(!pack) return null;
    const q = pack.bank.concat(pack.sections.map(s => s.checkpoint)).find(q => q.concept === concept && !t.asked.some(s => M.similarity(s, q.stem) > 0.9));
    return q ? Quiz.validate(q, t) : null;
  };
})();
